/*
 * Copyright (c) 2026. Amarula Solutions
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.googlesource.gerrit.plugins.reviewai.settings;

import java.util.Map;

public class Settings {
  public static final String GERRIT_PATCH_SET_FILENAME = "/PATCHSET_LEVEL";
  public static final String GERRIT_COMMIT_MESSAGE_FILENAME = "/COMMIT_MSG";
  public static final String GERRIT_DEFAULT_MESSAGE_DONE = "Done";
  public static final String GERRIT_DEFAULT_MESSAGE_PATCH_SET = "Patch Set";
  public static final String GERRIT_DEFAULT_MESSAGE_COMMENTS = "comments";
  public static final String GERRIT_AUTOGENERATED_PREFIX = "autogenerated:";
  public static final Map<String, String> COMMIT_MESSAGE_FILTER_OUT_PREFIXES =
      Map.of(
          "PARENT", "Parent:",
          "AUTHOR", "Author:",
          "AUTHOR_DATE", "AuthorDate:",
          "COMMIT", "Commit:",
          "COMMIT_DATE", "CommitDate:",
          "CHANGE_ID", "Change-Id:");
  public static final String GERRIT_COMMIT_MESSAGE_PREFIX = "Subject: ";

  public static final String OPENAI_ROLE_USER = "user";
  public static final String OPENAI_ROLE_ASSISTANT = "assistant";

  /**
   * Whether a path is one of Gerrit's own placeholders rather than a file of the revision.
   *
   * <p>{@code /PATCHSET_LEVEL} names the change and {@code /COMMIT_MSG} names its commit message.
   * Both are valid comment targets whatever the revision contains, so they must never be treated as
   * a file the revision has stopped having - a commit-message concern is not stale just because the
   * patch set lists no such file, and the patch set only lists {@code /COMMIT_MSG} in suggest mode.
   *
   * <p>The commit-message path is matched by suffix because a topic review prefixes every filename
   * with the change it came from, so the concern carries {@code <prefix>/COMMIT_MSG}.
   */
  public static boolean isGerritNonFilePath(String filename) {
    return filename != null
        && (GERRIT_PATCH_SET_FILENAME.equals(filename)
            || filename.endsWith(GERRIT_COMMIT_MESSAGE_FILENAME));
  }
}
